#!/usr/bin/env bash
#
# bootstrap creates symlinks for all dotfiles in this directory to $HOME

cd "$(dirname "$0")/.."
export DOTFILES_ROOT=$(pwd -P)
if [[ -n "$CODESPACES" ]]; then
  export DOTFILES_DEST=$DOTFILES_ROOT
else
  export DOTFILES_DEST=$HOME
fi
set -e # -e: exit on error

echo ''

info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

user () {
  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}


setup_gitconfig () {
  if ! [ -f git/gitconfig.local.symlink ]
  then
    info 'setup gitconfig'

    git_credential='cache'
    if [ "$(uname -s)" == "Darwin" ]
    then
      git_credential='osxkeychain'
    fi

    user ' - What is your github author name?'
    read -e git_authorname
    user ' - What is your github author email?'
    read -e git_authoremail

    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/gitconfig.local.symlink.example > git/gitconfig.local.symlink

    success 'gitconfig'
  fi
}

link_file () {
  local src=$1 dst=$2

  local overwrite= backup= skip=
  local action=

  if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
  then

    if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
    then

      local currentSrc="$(readlink $dst)"

      if [ "$currentSrc" == "$src" ]
      then

        skip=true;

      else

        user "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
        [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
        read -n 1 action

        case "$action" in
          o )
            overwrite=true;;
          O )
            overwrite_all=true;;
          b )
            backup=true;;
          B )
            backup_all=true;;
          s )
            skip=true;;
          S )
            skip_all=true;;
          * )
            ;;
        esac

      fi

    fi

    overwrite=${overwrite:-$overwrite_all}
    backup=${backup:-$backup_all}
    skip=${skip:-$skip_all}

    if [ "$overwrite" == "true" ]
    then
      rm -rf "$dst"
      success "removed $dst"
    fi

    if [ "$backup" == "true" ]
    then
      mv "$dst" "${dst}.backup"
      success "moved $dst to ${dst}.backup"
    fi

    if [ "$skip" == "true" ]
    then
      success "skipped $src"
    fi
  fi

  if [ "$skip" != "true" ]  # "false" or empty
  then
    ln -s "$1" "$2"
    success "linked $1 to $2"
  fi
}

install_dotfiles () {
  info 'installing dotfiles'

  local overwrite_all=${1:-false} backup_all=false skip_all=false

  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -not -path '*.git*')
  do
    dst="$DOTFILES_DEST/.$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done
}

install_mac_deps () {
  # Set macOS defaults
  $DOTFILES_ROOT/macos/set-defaults.sh

  # Install homebrew
  $DOTFILES_ROOT/homebrew/install.sh 2>&1

  # Upgrade homebrew
  echo "› brew update"
  brew update

  # Install software
  echo "› $DOTFILES_ROOT/script/install"
  $DOTFILES_ROOT/script/install
}


if [[ -n "$CODESPACES" ]]; then
  echo 'Setting up Codespaces dotfiles...'

  # Install zsh if not already installed
  if ! command -v zsh &> /dev/null; then
    echo "Installing zsh..."
    sudo apt-get update -qq
    sudo apt-get install -y zsh
    success "zsh installed"
  else
    success "zsh already installed"
  fi

  # Install fonts for p10k glyphs
  echo "Installing Meslo Nerd Font for p10k glyphs..."
  mkdir -p ~/.local/share/fonts
  cd ~/.local/share/fonts
  
  # Download Meslo Nerd Font files
  curl -fLo "MesloLGS NF Regular.ttf" https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf
  curl -fLo "MesloLGS NF Bold.ttf" https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf
  curl -fLo "MesloLGS NF Italic.ttf" https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf
  curl -fLo "MesloLGS NF Bold Italic.ttf" https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf
  
  # Refresh font cache
  fc-cache -f
  cd "$DOTFILES_ROOT"
  success "Meslo Nerd Font installed"

  # Set ZSH environment variable before running install
  export ZSH="$HOME/.oh-my-zsh"
  
  # Install oh-my-zsh and powerlevel10k
  bash "$DOTFILES_ROOT/zsh/install"
  
  # Copy zsh configuration files
  cat $DOTFILES_ROOT/zsh/zshrc.symlink > $HOME/.zshrc
  cat $DOTFILES_ROOT/zsh/.p10k.zsh > $HOME/.p10k.zsh

  # Change default shell to zsh
  if [ "$SHELL" != "$(which zsh)" ]; then
    echo "Changing default shell to zsh..."
    sudo chsh -s $(which zsh) $(whoami)
    success "Default shell changed to zsh"
  fi

  echo ''
  echo '  Codespaces setup finished!'
  echo '  Please restart your terminal or run: exec zsh'
# If we're on a Mac, let's install and setup other deps
elif [ "$(uname -s)" == "Darwin" ]
then
  if ! [ -f git/gitconfig.local.symlink ]
  then
    setup_gitconfig
  fi

  install_dotfiles

  info "installing dependencies"
  {
    install_mac_deps &&
    success "dependencies installed"
  } || {
    fail "error installing dependencies"
  }

  echo ''
  echo '  All installed!'
fi
