#!/usr/bin/env bash
#
# bootstrap creates symlinks for all dotfiles in this directory to $HOME

set -e

cd "$(dirname "$0")/.."
export DOTFILES_ROOT
DOTFILES_ROOT="$(pwd -P)"
if [[ -n "$CODESPACES" ]]; then
  export DOTFILES_DEST="$DOTFILES_ROOT"
else
  export DOTFILES_DEST="$HOME"
fi

echo ''

info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

user () {
  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit 1
}


setup_gitconfig () {
  local gitconfig_local='git/gitconfig.local.symlink'
  local gitconfig_source='git/gitconfig.local.symlink.example'
  local gitconfig_temp git_authorname='' git_authoremail='' git_config_status
  local git_credential='' platform_git_credential='cache'
  local write_git_credential=false
  if [ "$(uname -s)" == "Darwin" ]
  then
    platform_git_credential='osxkeychain'
  fi

  if [ -f "$gitconfig_local" ]
  then
    gitconfig_source="$gitconfig_local"

    if git_authorname=$(git config --file "$gitconfig_local" --get user.name)
    then
      :
    else
      git_config_status=$?
      if [ "$git_config_status" -ne 1 ]
      then
        fail 'unable to read gitconfig'
      fi
    fi

    if git_authoremail=$(git config --file "$gitconfig_local" --get user.email)
    then
      :
    else
      git_config_status=$?
      if [ "$git_config_status" -ne 1 ]
      then
        fail 'unable to read gitconfig'
      fi
    fi

    if git_credential=$(git config --file "$gitconfig_local" --get credential.helper)
    then
      :
    else
      git_config_status=$?
      if [ "$git_config_status" -ne 1 ]
      then
        fail 'unable to read gitconfig'
      fi
    fi
  fi

  if [ -n "$git_authorname" ] && [ -n "$git_authoremail" ]
  then
    return
  fi

  info 'setup gitconfig'

  while [ -z "$git_authorname" ]
  do
    user ' - What is your github author name?'
    read -r -e git_authorname
  done

  while [ -z "$git_authoremail" ]
  do
    user ' - What is your github author email?'
    read -r -e git_authoremail
  done

  if [ -z "$git_credential" ] || [ "$git_credential" = 'GIT_CREDENTIAL_HELPER' ]
  then
    git_credential="$platform_git_credential"
    write_git_credential=true
  fi
  gitconfig_temp=$(mktemp "${gitconfig_local}.XXXXXX")
  if ! cp "$gitconfig_source" "$gitconfig_temp" ||
    ! git config --file "$gitconfig_temp" user.name "$git_authorname" ||
    ! git config --file "$gitconfig_temp" user.email "$git_authoremail"
  then
    rm -f "$gitconfig_temp"
    fail 'unable to create gitconfig'
  fi

  if [ "$write_git_credential" = true ] &&
    ! git config --file "$gitconfig_temp" credential.helper "$git_credential"
  then
    rm -f "$gitconfig_temp"
    fail 'unable to create gitconfig'
  fi

  if ! mv "$gitconfig_temp" "$gitconfig_local"
  then
    rm -f "$gitconfig_temp"
    fail 'unable to create gitconfig'
  fi

  success 'gitconfig'
}

link_file () {
  local src=$1 dst=$2

  local overwrite= backup= skip=
  local action=

  if [[ -e "$dst" || -L "$dst" ]]
  then

    if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
    then

      local currentSrc
      currentSrc="$(readlink "$dst")"

      if [ "$currentSrc" == "$src" ]
      then

        skip=true;

      else

        user "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
        [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
        read -n 1 action

        case "$action" in
          o )
            overwrite=true;;
          O )
            overwrite_all=true;;
          b )
            backup=true;;
          B )
            backup_all=true;;
          s )
            skip=true;;
          S )
            skip_all=true;;
          * )
            ;;
        esac

      fi

    fi

    overwrite=${overwrite:-$overwrite_all}
    backup=${backup:-$backup_all}
    skip=${skip:-$skip_all}

    if [ "$overwrite" == "true" ]
    then
      rm -rf "$dst"
      success "removed $dst"
    fi

    if [ "$backup" == "true" ]
    then
      mv "$dst" "${dst}.backup"
      success "moved $dst to ${dst}.backup"
    fi

    if [ "$skip" == "true" ]
    then
      success "skipped $src"
    fi
  fi

  if [ "$skip" != "true" ]  # "false" or empty
  then
    ln -s "$1" "$2"
    success "linked $1 to $2"
  fi
}

install_dotfiles () {
  info 'installing dotfiles'

  local overwrite_all=${1:-false} backup_all=false skip_all=false
  local src dst

  while IFS= read -r -d '' src; do
    dst="$DOTFILES_DEST/.$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done < <(
    find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' \
      -not -path '*.git*' -print0
  )
}

install_mac_deps () {
  # Set macOS defaults
  "$DOTFILES_ROOT/macos/set-defaults.sh"

  # Install software
  echo "› $DOTFILES_ROOT/script/install"
  "$DOTFILES_ROOT/script/install"
}


if [[ -n "$CODESPACES" ]]; then
  echo 'Setting up Codespaces dotfiles...'

  # Install zsh if not already installed
  if ! command -v zsh &> /dev/null; then
    echo "Installing zsh..."
    sudo apt-get update -qq
    sudo apt-get install -y zsh
    success "zsh installed"
  else
    success "zsh already installed"
  fi

  # Install fonts for p10k glyphs when missing.
  font_dir="$HOME/.local/share/fonts"
  mkdir -p "$font_dir"
  fonts_installed=false
  font_variants=("Regular" "Bold" "Italic" "Bold Italic")
  for variant in "${font_variants[@]}"; do
    font_path="$font_dir/MesloLGS NF ${variant}.ttf"
    if [[ ! -f "$font_path" ]]; then
      echo "Installing Meslo Nerd Font ${variant}..."
      curl -fLo "$font_path" \
        "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20${variant// /%20}.ttf"
      fonts_installed=true
    fi
  done

  if [[ "$fonts_installed" == "true" ]]; then
    fc-cache -f
    success "Meslo Nerd Font installed"
  else
    success "Meslo Nerd Font already installed"
  fi

  # Set ZSH environment variable before running install
  export ZSH="$HOME/.oh-my-zsh"
  
  # Install oh-my-zsh and powerlevel10k
  "$DOTFILES_ROOT/zsh/install.sh"
  
  # Symlink zsh configuration files
  ln -sf "$DOTFILES_ROOT/zsh/zshrc.symlink" "$HOME/.zshrc"
  ln -sf "$DOTFILES_ROOT/zsh/.p10k.zsh" "$HOME/.p10k.zsh"
  success "zsh configuration files symlinked"

  # Change default shell to zsh
  zsh_path="$(command -v zsh)"
  if [ "$SHELL" != "$zsh_path" ]; then
    echo "Changing default shell to zsh..."
    sudo chsh -s "$zsh_path" "$(whoami)"
    success "Default shell changed to zsh"
  fi

  echo ''
  echo '  Codespaces setup finished!'
  echo '  Please restart your terminal or run: exec zsh'
# If we're on a Mac, let's install and setup other deps
elif [ "$(uname -s)" == "Darwin" ]
then
  setup_gitconfig

  install_dotfiles

  info "installing dependencies"
  {
    install_mac_deps &&
    success "dependencies installed"
  } || {
    fail "error installing dependencies"
  }

  echo ''
  echo '  All installed!'
fi
