#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -euo pipefail

dotfiles_root="$(cd "$(dirname "$0")/.." && pwd -P)"

installers=(
  "$dotfiles_root/homebrew/install.sh"
  "$dotfiles_root/node/install.sh"
  "$dotfiles_root/zsh/install.sh"
)

for installer in "${installers[@]}"; do
  "$installer"
done
