#!/bin/sh

zshrc() {
  if [ ! -d $ZSH ]
  then
    # oh-my-zsh install
    echo "==========================================================="
    echo "             cloning oh-my-zsh                             "
    echo "-----------------------------------------------------------"
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  fi

  if [ ! -d ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k ]
  then
    # powerlevel10k install
    echo "==========================================================="
    echo "             cloning powerlevel10k theme                   "
    echo "-----------------------------------------------------------"
      git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
  fi
}

zshrc
